name: Dave
favicon: null
layout_spectrum: 0.4381
typography_spectrum: 0.32764
title: Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f3f3'
    - '#ff9205'
    - '#25262a'
    - '#5d5d5d'
    - '#979797'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
