name: Dave Leal
favicon: null
layout_spectrum: 0.88148
typography_spectrum: 0.30976
title: Dave Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9d9d9'
    - '#d2a480'
    - '#17120f'
    - '#7e2727'
    - '#93684b'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
