name: Dave
favicon: null
layout_spectrum: 0.50528
typography_spectrum: 0.32764
title: Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cccccc'
    - '#383b2a'
    - '#5e624a'
    - '#0a0a08'
    - '#8f8b7c'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
