name: Dave Leal
favicon: null
layout_spectrum: 0.14542
typography_spectrum: 0.30976
title: David Leal Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f6f6f6'
    - '#f8f8f8'
    - '#fdfdfd'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
